from msp_constants import *
from msp_types import *

def MakeFLAGID(RR, BIT):
    return (RR << 16) | (1 << BIT)

def StarFLAGID(RR, BIT):
    return msp_FLAGID(MakeFLAGID(RR, BIT) ^ 0x80000000)

def MakeREGID(RR, MASK):
    return msp_REGID((RR << 16) | MASK)

def OffsREGID(RR, MASK, offs):
    return msp_REGID((offs << 28) | (RR << 16) | MASK)

def MakeALIAS(RR):
    return msp_REGID((RR << 16) | 0xFFFF)

mspF_CURRENT_AREA = MakeFLAGID(mspRR_CONFIG1, 13)
mspF_CURRENT_AREA_B = mspF_CURRENT_AREA
mspF_CURRENT_AREA_A = StarFLAGID(mspRR_CONFIG1, 13)
mspF_LOWER_CLOCK_SELECT = MakeFLAGID(mspRR_CONFIG5, 15)
mspF_DOUBLE_SAMPLE_FREQUENCY = MakeFLAGID(mspRR_CONFIG5, 11)
mspF_EXPANDED_ZERO_CROSSING_ENABLED = mspF_DOUBLE_SAMPLE_FREQUENCY
mspF_GAP_CHECK_ENABLED = MakeFLAGID(mspRR_CONFIG5, 8)
mspF_256WORD_BOUNDARY_DISABLE = MakeFLAGID(mspRR_CONFIG2, 10)
mspF_ENHANCED_MODE = MakeFLAGID(mspRR_CONFIG3, 15)

mspF_ENHANCED_CPU_ACCESS = MakeFLAGID(mspRR_CONFIG6, 14)


#BC mode flags
mspF_MESSAGE_STOP_ON_ERROR = MakeFLAGID(mspRR_CONFIG1, 12)
mspF_FRAME_STOP_ON_ERROR = MakeFLAGID(mspRR_CONFIG1, 11)
mspF_STATUS_SET_STOP_ON_MESSSAGE = MakeFLAGID(mspRR_CONFIG1, 10)
mspF_STATUS_SET_STOP_ON_FRAME = MakeFLAGID(mspRR_CONFIG1, 9)
mspF_FRAME_AUTOREPEAT = MakeFLAGID(mspRR_CONFIG1, 8)
mspF_EXTERNAL_TRIGGER_ENABLED = MakeFLAGID(mspRR_CONFIG1, 7)
mspF_INTERNAL_TRIGGER_ENABLED = MakeFLAGID(mspRR_CONFIG1, 6)
mspF_MESSAGE_GAP_TIMER_ENABLED = MakeFLAGID(mspRR_CONFIG1, 5)
mspF_RETRY_ENABLED = MakeFLAGID(mspRR_CONFIG1, 4)
mspF_DOUBLE_RETRY = MakeFLAGID(mspRR_CONFIG1, 3)
mspF_BC_ENABLED = MakeFLAGID(mspRR_CONFIG1, 2)
mspF_BC_FRAME_IN_PROGRESS = MakeFLAGID(mspRR_CONFIG1, 1)
mspF_BC_MESSAGE_IN_PROGRESS = MakeFLAGID(mspRR_CONFIG1, 0)
mspF_EXPANDED_BC_CONTROL_WORD = MakeFLAGID(mspRR_CONFIG4, 12)
mspF_BROADCAST_MASK_ENABLED = MakeFLAGID(mspRR_CONFIG4, 11)
mspF_RETRY_IF_1553A_AND_MESSAGE_ERROR = MakeFLAGID(mspRR_CONFIG4, 10)
mspF_RETRY_IF_STATUS_SET = MakeFLAGID(mspRR_CONFIG4, 9)
mspF_RETRY1_AT_ALT_BUS = MakeFLAGID(mspRR_CONFIG4, 8)
mspF_RETRY2_AT_ALT_BUS = MakeFLAGID(mspRR_CONFIG4, 7)
mspF_VALID_ERROR_BIT_NO_DATA = MakeFLAGID(mspRR_CONFIG4, 6)
mspF_VALID_BUSY_BIT_NO_DATA = MakeFLAGID(mspRR_CONFIG4, 5)

#lve RT, RT/MM, MM flags
mspF_INCREMENT_ON_EOM = MakeFLAGID(mspRR_CONFIG6, 13)

#RT mode flags
mspF_NOT_ACCEPT_DYNAMIC_BUS_CONTROL = MakeFLAGID(mspRR_CONFIG1, 11)
mspF_ACCEPT_DYNAMIC_BUS_CONTROL = StarFLAGID(mspRR_CONFIG1, 11)
mspF_NOT_BUSY = MakeFLAGID(mspRR_CONFIG1, 10)
mspF_BUSY = StarFLAGID(mspRR_CONFIG1, 10)
mspF_NOT_SERVICE_REQUEST = MakeFLAGID(mspRR_CONFIG1, 9)
mspF_SERVICE_REQUEST = StarFLAGID(mspRR_CONFIG1, 9)
mspF_NOT_SUBSYSTEM_FLAG = MakeFLAGID(mspRR_CONFIG1, 8)
mspF_SUBSYSTEM_FLAG = StarFLAGID(mspRR_CONFIG1, 8)
mspF_NOT_RTFLAG = MakeFLAGID(mspRR_CONFIG1, 7)
mspF_RTFLAG = StarFLAGID(mspRR_CONFIG1, 7)
mspF_RT_MESSAGE_IN_PROGRESS = MakeFLAGID(mspRR_CONFIG1, 0)

mspF_S10 = MakeFLAGID(mspRR_CONFIG1, 11)
mspF_S09 = MakeFLAGID(mspRR_CONFIG1, 10)
mspF_S08 = MakeFLAGID(mspRR_CONFIG1, 9)
mspF_S07 = MakeFLAGID(mspRR_CONFIG1, 8)
mspF_S06 = MakeFLAGID(mspRR_CONFIG1, 7)
mspF_S05 = MakeFLAGID(mspRR_CONFIG1, 6)
mspF_S04 = MakeFLAGID(mspRR_CONFIG1, 5)
mspF_S03 = MakeFLAGID(mspRR_CONFIG1, 4)
mspF_S02 = MakeFLAGID(mspRR_CONFIG1, 3)
mspF_S01 = MakeFLAGID(mspRR_CONFIG1, 2)
mspF_S00 = MakeFLAGID(mspRR_CONFIG1, 1)
mspF_ALTSTATUS_MESSAGE_ERROR = mspF_S10
mspF_ALTSTATUS_INSTRUMENTATION = mspF_S09
mspF_ALTSTATUS_SERVICE_REQUEST = mspF_S08
mspF_ALTSTATUS_RESERVED_12 = mspF_S07
mspF_ALTSTATUS_RESERVED_13 = mspF_S06
mspF_ALTSTATUS_RESERVED_14 = mspF_S05
mspF_ALTSTATUS_BROADCAST_COMMAND_RECEIVED = mspF_S04
mspF_ALTSTATUS_BUSY = mspF_S03
mspF_ALTSTATUS_SUBSYSTEM_FLAG = mspF_S02
mspF_ALTSTATUS_ACCEPT_DYNAMIC_BUS_CONTROL = mspF_S01
mspF_ALTSTATUS_TERMINAL_FLAG = mspF_S00

mspF_MULTIRT_ENABLE = MakeFLAGID(mspRR_CONFIG2, 14)
mspF_BUSY_BIT_LOOKUP_TABLE_ENABLE = MakeFLAGID(mspRR_CONFIG2, 13)
mspF_DOUBLE_BUFFERING_ENABLE = MakeFLAGID(mspRR_CONFIG2, 12)
mspF_OVERWRITE_INVALID_DATA = MakeFLAGID(mspRR_CONFIG2, 11)
mspF_CLEAR_TIME_TAG_ON_SYNCHRONIZE = MakeFLAGID(mspRR_CONFIG2, 6)
mspF_LOAD_TIME_TAG_ON_SYNCHRONIZE = MakeFLAGID(mspRR_CONFIG2, 5)
mspF_CLEAR_SERVICE_REQUEST = MakeFLAGID(mspRR_CONFIG2, 2)
mspF_ENHANCED_RT_MEMORY_MANAGEMENT = MakeFLAGID(mspRR_CONFIG2, 1)
mspF_SEPARATE_BROADCAST_DATA = MakeFLAGID(mspRR_CONFIG2, 0)
mspF_ILLEGALIZATION_DISABLED = MakeFLAGID(mspRR_CONFIG3, 7)
mspF_OVERRIDE_MODE_CODE_BIT_ERROR = MakeFLAGID(mspRR_CONFIG3, 6)
mspF_ALTERNATE_RT_STATUS_WORD_ENABLED = MakeFLAGID(mspRR_CONFIG3, 5)
mspF_ILLEGAL_RECEIVE_TRANSFER_DISABLE = MakeFLAGID(mspRR_CONFIG3, 4)
mspF_BUSY_RECEIVE_TRANSFER_DISABLE = MakeFLAGID(mspRR_CONFIG3, 3)
mspF_RTF_WRAP_ENABLE = MakeFLAGID(mspRR_CONFIG3, 2)
mspF_1553A_MODE_CODES_ENABLED = MakeFLAGID(mspRR_CONFIG3, 1)
mspF_ENHANCED_MODE_CODE_HANDLING = MakeFLAGID(mspRR_CONFIG3, 0)
mspF_EXTERNAL_BIT_WORD_ENABLE = MakeFLAGID(mspRR_CONFIG4, 15)
mspF_INHIBIT_BIT_WORD_TRANSMIT_IF_BUSY = MakeFLAGID(mspRR_CONFIG4, 14)
mspF_MODE_CODE_OVERRIDE_BUSY = MakeFLAGID(mspRR_CONFIG4, 13)
mspF_BROADCAST_DISABLED = MakeFLAGID(mspRR_CONFIG5, 7)

#MT mode flags
mspF_MONITOR_TRIGGER_ENABLED = MakeFLAGID(mspRR_CONFIG1, 11)
mspF_START_ON_TRIGGER = MakeFLAGID(mspRR_CONFIG1, 10)
mspF_STOP_ON_TRIGGER = MakeFLAGID(mspRR_CONFIG1, 9)
mspF_EXTERNAL_TRIGGER_ENABLED = MakeFLAGID(mspRR_CONFIG1, 7)
mspF_MONITOR_ENABLED = MakeFLAGID(mspRR_CONFIG1, 2)
mspF_MONITOR_TRIGGERED = MakeFLAGID(mspRR_CONFIG1, 1)
mspF_MONITOR_ACTIVE = MakeFLAGID(mspRR_CONFIG1, 0)
mspF_1553A_MODE_CODES_ENABLED = MakeFLAGID(mspRR_CONFIG3, 1)
mspF_MONITOR_TAG_GAP_OPTION = MakeFLAGID(mspRR_CONFIG4, 4)
mspF_BROADCAST_DISABLED = MakeFLAGID(mspRR_CONFIG5, 7)

#Interrupt control flags
mspF_ENHANCED_INTERRUPTS = MakeFLAGID(mspRR_CONFIG2, 15)
mspF_INTERRUPT_STATUS_AUTO_CLEAR = MakeFLAGID(mspRR_CONFIG2, 4)
mspF_LEVEL_INTERRUPTS = MakeFLAGID(mspRR_CONFIG2, 3)
mspF_PULSE_INTERRUPTS = StarFLAGID(mspRR_CONFIG2, 3)